import type { Readable } from 'node:stream';

export type PutBody = Buffer | Uint8Array | Readable;

export type PutResult = {
  key: string;
  byteSize: number;
  mime: string;
};

export type BlobStat = {
  key: string;
  byteSize: number;
  modifiedAt: number;
};

/**
 * The storage seam. LocalDiskStore backs development; an S3Store lands later
 * without anything above this interface changing.
 *
 * Two rules the whole product depends on:
 *  1. There are no public URLs. Every read is auth-checked by the app, so the
 *     store only ever hands back a stream (or a local path for ffmpeg/Remotion).
 *  2. Keys are prefixed `memorial/{id}/…` so a hard delete is a single
 *     `deletePrefix` — deletion has to be real, not a hidden flag.
 *
 * Content type is *not* persisted by the store; it lives on the owning DB row
 * (`media_assets.mime`). Blobs stay dumb bytes.
 */
export interface BlobStore {
  readonly id: string;

  put(key: string, body: PutBody, mime: string): Promise<PutResult>;
  getStream(key: string): Promise<Readable>;
  /** Present only for stores backed by a real filesystem (ffmpeg wants paths). */
  getPath?(key: string): string;
  exists(key: string): Promise<boolean>;
  stat(key: string): Promise<BlobStat | undefined>;
  list(prefix: string): Promise<string[]>;
  delete(key: string): Promise<void>;
  /** Hard delete of everything under a prefix. Returns how many blobs went. */
  deletePrefix(prefix: string): Promise<number>;
}

export class BlobNotFoundError extends Error {
  constructor(readonly key: string) {
    super(`Blob not found: ${key}`);
    this.name = 'BlobNotFoundError';
  }
}

export class InvalidBlobKeyError extends Error {
  constructor(
    readonly key: string,
    reason: string,
  ) {
    super(`Invalid blob key ${JSON.stringify(key)}: ${reason}`);
    this.name = 'InvalidBlobKeyError';
  }
}

/** Conservative on purpose: keys are generated by us, never by users. */
const SEGMENT_RE = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
const MAX_KEY_LENGTH = 512;

/**
 * Normalise and validate a blob key. Rejects anything that could escape the
 * storage root: absolute paths, `..`, backslashes, NUL bytes, control chars.
 * Returns the canonical key (collapsed slashes, no leading/trailing slash).
 */
export function sanitizeKey(key: string): string {
  if (typeof key !== 'string' || key.length === 0) {
    throw new InvalidBlobKeyError(String(key), 'key must be a non-empty string');
  }
  if (key.length > MAX_KEY_LENGTH) {
    throw new InvalidBlobKeyError(key, `key exceeds ${MAX_KEY_LENGTH} characters`);
  }
  // eslint-disable-next-line no-control-regex
  if (/[\u0000-\u001f\u007f]/.test(key)) {
    throw new InvalidBlobKeyError(key, 'key contains control characters');
  }
  if (key.includes('\\')) throw new InvalidBlobKeyError(key, 'backslashes are not allowed');
  if (key.startsWith('/')) throw new InvalidBlobKeyError(key, 'key must be relative');
  if (/^[A-Za-z]:/.test(key)) throw new InvalidBlobKeyError(key, 'key must not be a drive path');

  const segments = key.split('/').filter((s) => s.length > 0);
  if (segments.length === 0) throw new InvalidBlobKeyError(key, 'key has no path segments');
  for (const segment of segments) {
    if (segment === '.' || segment === '..') {
      throw new InvalidBlobKeyError(key, 'path traversal segments are not allowed');
    }
    if (!SEGMENT_RE.test(segment)) {
      throw new InvalidBlobKeyError(
        key,
        `segment ${JSON.stringify(segment)} must match ${SEGMENT_RE}`,
      );
    }
  }
  return segments.join('/');
}

/**
 * Prefixes may name a directory, so a trailing slash is fine and a single
 * segment is fine. Same traversal rules otherwise.
 */
export function sanitizePrefix(prefix: string): string {
  const trimmed = prefix.replace(/\/+$/, '');
  return sanitizeKey(trimmed);
}

/** Canonical key layout. Keeping this in one place is what makes purge safe. */
export const blobKeys = {
  memorialPrefix: (memorialId: string) => `memorial/${memorialId}`,
  original: (memorialId: string, assetId: string, ext: string) =>
    `memorial/${memorialId}/original/${assetId}.${ext}`,
  variant: (memorialId: string, assetId: string, variant: string, ext: string) =>
    `memorial/${memorialId}/variant/${variant}/${assetId}.${ext}`,
  render: (memorialId: string, renderJobId: string, ext = 'mp4') =>
    `memorial/${memorialId}/render/${renderJobId}.${ext}`,
};
