/**
 * The cards, as plain text.
 *
 * Funeral homes run on email and on paper. Some will print the page; some want
 * six lines they can paste into a message to the person on the sound desk. This
 * is the same words, generated by the same code, with no markup to lose.
 */
import type { CutName, RenderPreset } from '@col/schemas';
import {
  authorizeOrganizer,
  buildDirectorCard,
  buildTimingCard,
  cardToText,
  formatServiceDate,
  latestProject,
  latestRender,
  musicChoice,
  projectCut,
  projectEdl,
  summariseMusic,
} from '@col/core';
import { getById, memorials } from '@col/db';
import { getPack } from '@col/tradition-packs';
import { db } from '@/server/db';
import { readSession } from '@/server/session';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const PRESETS: RenderPreset[] = ['final1080', 'backup720', 'draft360'];

export async function GET(
  request: Request,
  { params }: { params: Promise<{ memorialId: string }> },
): Promise<Response> {
  const { memorialId } = await params;

  const session = await readSession();
  if (!session || !authorizeOrganizer(db(), session, memorialId).ok) {
    return new Response('Not available.', {
      status: 403,
      headers: { 'cache-control': 'no-store' },
    });
  }

  const memorial = getById(db(), memorials, memorialId);
  if (!memorial || memorial.deletedAt != null) {
    return new Response('Not available.', {
      status: 403,
      headers: { 'cache-control': 'no-store' },
    });
  }

  const url = new URL(request.url);
  const cut: CutName = url.searchParams.get('cut') === 'family' ? 'family' : 'service';
  const requested = url.searchParams.get('preset') ?? 'final1080';
  const preset = (
    PRESETS.includes(requested as RenderPreset) ? requested : 'final1080'
  ) as RenderPreset;
  const kind = url.searchParams.get('kind') === 'timing' ? 'timing' : 'director';

  const project = latestProject(db(), memorialId);
  const edl = projectEdl(project);
  const timeline = edl ? projectCut(edl, cut) : undefined;
  const render = latestRender(db(), memorialId, cut, preset);
  const durationSec = render?.durationSec ?? timeline?.totalSec ?? 0;

  const text =
    kind === 'timing'
      ? timingText(memorial.decedentName, memorialId, cut, durationSec)
      : directorText(memorial, memorialId, cut, preset, durationSec, render?.ffprobeMeta);

  return new Response(text, {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'private, no-store',
      'content-disposition': `inline; filename="${kind}-card.txt"`,
    },
  });
}

function timingText(
  decedentName: string,
  memorialId: string,
  cut: CutName,
  durationSec: number,
): string {
  const project = latestProject(db(), memorialId);
  const choice = musicChoice(db(), project);
  const edl = projectEdl(project);
  if (choice.mode !== 'sideloaded') {
    return 'The music is inside this video. Nobody needs to play anything alongside it.';
  }
  return cardToText(
    buildTimingCard({
      decedentName,
      songTitle: choice.selection?.sideloadedTitle ?? 'The song the family chose',
      ...(choice.selection?.sideloadedArtist
        ? { songArtist: choice.selection.sideloadedArtist }
        : {}),
      durationSec,
      ...(edl?.audio.beatGrid?.bpm ? { bpm: edl.audio.beatGrid.bpm } : {}),
    }),
  );
}

function directorText(
  memorial: {
    decedentName: string;
    traditionSlug: string;
    serviceDate: number | null;
    timezone: string;
  },
  memorialId: string,
  cut: CutName,
  preset: RenderPreset,
  durationSec: number,
  ffprobeMeta: unknown,
): string {
  const probe = (ffprobeMeta ?? {}) as { width?: number; height?: number };
  const pack = getPack(memorial.traditionSlug);
  const music = summariseMusic(db(), latestProject(db(), memorialId));

  return cardToText(
    buildDirectorCard({
      decedentName: memorial.decedentName,
      cut,
      preset,
      durationSec,
      ...(probe.width ? { width: probe.width } : {}),
      ...(probe.height ? { height: probe.height } : {}),
      audioMode: music.mode,
      ...(pack.mediaPlacement[0] ? { placementNote: pack.mediaPlacement[0] } : {}),
      ...(memorial.serviceDate
        ? { serviceDateLabel: formatServiceDate(memorial.serviceDate, memorial.timezone) }
        : {}),
    }),
  );
}
