/**
 * `pnpm music:build` — the bundled music library, synthesised from scratch.
 *
 * WHY THIS EXISTS AT ALL
 *
 * A tribute video that a family can share — email it to an aunt, put it on the
 * funeral home's page — cannot contain a commercial recording without a
 * per-song synchronisation licence. That leaves two honest options, and this
 * script is the first of them: original music, written and performed by nobody,
 * generated by arithmetic, released CC0, and therefore genuinely free of any
 * claim anyone could make against a grieving family.
 *
 * It is not a substitute for a real composer. It is a floor: eight quiet,
 * unobtrusive pieces that will not embarrass a room, with provenance nobody has
 * to take on trust because the provenance is this file.
 *
 * HOW IT WORKS
 *
 *  - a small additive synthesiser (wavetable oscillators, ADSR envelopes,
 *    per-partial decay) plays a slow chord progression at a known tempo;
 *  - four voices: bass, sustained pad, a plain melody, and — on some pieces —
 *    an arpeggio;
 *  - a Schroeder reverb (four combs, two allpasses) puts it in a room;
 *  - every random choice comes from a seeded PRNG, so re-running this produces
 *    byte-identical audio;
 *  - the result is written as 16-bit WAV and encoded to AAC by ffmpeg.
 *
 * Because the tempo is chosen rather than detected, each track's beat grid is
 * exact: the timing engine snaps slide changes to phrase boundaries that really
 * are where the music turns over.
 *
 * Output: content/music-library/<slug>/{audio.m4a,meta.json,LICENSE.txt}
 */
/* eslint-disable no-console */
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeWav } from '../packages/media/src/wav';
import { beatGridFromBpm } from '../packages/media/src/beat-grid';
import { runFfmpeg, runFfprobe } from '../packages/media/src/ffmpeg';
import type { MusicTrackMeta } from '../packages/schemas/src/music';

const here = path.dirname(fileURLToPath(import.meta.url));
export const MUSIC_LIBRARY_DIR = path.resolve(here, '..', 'content', 'music-library');

const SAMPLE_RATE = 44_100;
/** AAC at 96 kbps is transparent enough for quiet acoustic material, and keeps
 *  a three-minute track comfortably under 3 MB so it can live in the repo. */
const BITRATE = '96k';

/* -------------------------------------------------------------------------- */
/* determinism                                                                 */
/* -------------------------------------------------------------------------- */

/** mulberry32: tiny, fast, and identical on every machine and Node version. */
function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* -------------------------------------------------------------------------- */
/* notes                                                                       */
/* -------------------------------------------------------------------------- */

const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'] as const;

/** MIDI note number → frequency, A4 = 440 Hz = MIDI 69. */
function hz(midi: number): number {
  return 440 * Math.pow(2, (midi - 69) / 12);
}

/** "F3" → MIDI number. Written this way so progressions read like music. */
function midi(name: string): number {
  const match = /^([A-G]#?)(-?\d)$/.exec(name);
  if (!match) throw new Error(`unparseable note: ${name}`);
  const index = NOTE_NAMES.indexOf(match[1] as (typeof NOTE_NAMES)[number]);
  return index + 12 * (Number(match[2]) + 1);
}

/* -------------------------------------------------------------------------- */
/* the wavetable oscillator                                                    */
/* -------------------------------------------------------------------------- */

const TABLE_BITS = 12;
const TABLE_SIZE = 1 << TABLE_BITS;
const SINE = new Float32Array(TABLE_SIZE + 1);
for (let i = 0; i <= TABLE_SIZE; i += 1) SINE[i] = Math.sin((2 * Math.PI * i) / TABLE_SIZE);

/** Linear-interpolated sine lookup. Phase is in turns (0..1). */
function sine(phase: number): number {
  const wrapped = phase - Math.floor(phase);
  const scaled = wrapped * TABLE_SIZE;
  const index = scaled | 0;
  const frac = scaled - index;
  const a = SINE[index] as number;
  const b = SINE[index + 1] as number;
  return a + (b - a) * frac;
}

/* -------------------------------------------------------------------------- */
/* voices                                                                      */
/* -------------------------------------------------------------------------- */

type Timbre = {
  /** Harmonic number → relative amplitude. */
  partials: readonly number[];
  /** Seconds to full volume. A hammer is 5 ms; a bowed string is most of a second. */
  attackSec: number;
  /** Seconds for the fundamental to fall by 60 dB. */
  decaySec: number;
  /** Sustain level after the decay, 0..1. Struck instruments sustain at 0. */
  sustain: number;
  releaseSec: number;
  /** How much faster each successive partial dies away. */
  partialDecay: number;
  /** Cents of detune between the two stacked oscillators. Warmth, not chorus. */
  detuneCents: number;
};

/** Struck and left to ring: what carries a melody without insisting on one. */
const PIANO: Timbre = {
  partials: [1, 0.42, 0.22, 0.11, 0.06, 0.035, 0.02],
  attackSec: 0.006,
  decaySec: 2.6,
  sustain: 0,
  releaseSec: 1.6,
  partialDecay: 1.55,
  detuneCents: 3.5,
};

/** Softer, rounder, fewer upper partials: the low notes underneath everything. */
const BASS: Timbre = {
  partials: [1, 0.3, 0.12, 0.05],
  attackSec: 0.012,
  decaySec: 3.4,
  sustain: 0,
  releaseSec: 2.2,
  partialDecay: 1.35,
  detuneCents: 2,
};

/** Bowed and held. The thing that makes a room feel like a room. */
const PAD: Timbre = {
  partials: [1, 0.5, 0.28, 0.14, 0.07, 0.03],
  attackSec: 0.9,
  decaySec: 2.5,
  sustain: 0.55,
  releaseSec: 2.4,
  partialDecay: 1.2,
  detuneCents: 6,
};

/** A struck bell, used sparingly for the high arpeggios. */
const BELL: Timbre = {
  partials: [1, 0.28, 0.35, 0.14, 0.09],
  attackSec: 0.004,
  decaySec: 3.2,
  sustain: 0,
  releaseSec: 2.4,
  partialDecay: 1.15,
  detuneCents: 1.5,
};

type NoteEvent = {
  midi: number;
  startSec: number;
  /** How long the key is held. The tail continues past this. */
  holdSec: number;
  velocity: number;
  timbre: Timbre;
  /** −1 hard left, +1 hard right. Kept small: this is not a stereo demo. */
  pan: number;
};

/**
 * Render one note into the stereo buffers.
 *
 * ADSR on the fundamental, with each partial decaying faster than the one below
 * it — which is most of why a plucked string sounds like a plucked string and a
 * plain sine sounds like a hearing test.
 */
function renderNote(left: Float32Array, right: Float32Array, note: NoteEvent): void {
  const { timbre } = note;
  const start = Math.max(0, Math.round(note.startSec * SAMPLE_RATE));
  const hold = Math.max(1, Math.round(note.holdSec * SAMPLE_RATE));
  const release = Math.max(1, Math.round(timbre.releaseSec * SAMPLE_RATE));
  const total = Math.min(hold + release, left.length - start);
  if (total <= 0) return;

  const attack = Math.max(1, Math.round(timbre.attackSec * SAMPLE_RATE));
  const decay = Math.max(1, timbre.decaySec * SAMPLE_RATE);
  const base = hz(note.midi);
  const detune = Math.pow(2, timbre.detuneCents / 1200);

  const leftGain = Math.cos(((note.pan + 1) * Math.PI) / 4);
  const rightGain = Math.sin(((note.pan + 1) * Math.PI) / 4);

  // Two stacked oscillator stacks, a few cents apart. Phases start at zero so
  // the same note in two takes is the same waveform, which is what makes this
  // whole script reproducible.
  const phases = new Float64Array(timbre.partials.length * 2);
  const increments = new Float64Array(timbre.partials.length * 2);
  for (let p = 0; p < timbre.partials.length; p += 1) {
    // A touch of inharmonicity, as on a real string: upper partials sit very
    // slightly sharp, which is what stops this sounding like an organ.
    const harmonic = (p + 1) * (1 + 0.0004 * p * p);
    increments[p * 2] = (base * harmonic) / SAMPLE_RATE;
    increments[p * 2 + 1] = (base * detune * harmonic) / SAMPLE_RATE;
  }

  for (let i = 0; i < total; i += 1) {
    // Envelope on the fundamental.
    let amplitude: number;
    if (i < attack) amplitude = i / attack;
    else if (i < hold) {
      const decayed = Math.exp(-(i - attack) / decay);
      amplitude = timbre.sustain + (1 - timbre.sustain) * decayed;
    } else {
      const held = Math.exp(-(hold - attack) / decay);
      const level = timbre.sustain + (1 - timbre.sustain) * held;
      amplitude = level * Math.exp((-(i - hold) / release) * 3.5);
    }
    // Only after the attack: at i = 0 the envelope is legitimately zero, and
    // bailing out there would render every note as silence.
    if (i > attack && amplitude < 1e-5) break;

    let sample = 0;
    for (let p = 0; p < timbre.partials.length; p += 1) {
      const partialAmp =
        (timbre.partials[p] as number) *
        Math.exp((-(i - Math.min(i, attack)) / decay) * (Math.pow(timbre.partialDecay, p) - 1));
      if (partialAmp < 1e-4) continue;
      const a = (phases[p * 2] as number) + (increments[p * 2] as number) * i;
      const b = (phases[p * 2 + 1] as number) + (increments[p * 2 + 1] as number) * i;
      sample += partialAmp * (sine(a) + sine(b)) * 0.5;
    }

    const value = sample * amplitude * note.velocity * 0.16;
    const at = start + i;
    left[at] = (left[at] as number) + value * leftGain;
    right[at] = (right[at] as number) + value * rightGain;
  }
}

/* -------------------------------------------------------------------------- */
/* reverb                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * A plain Schroeder reverb: four parallel comb filters into two allpasses.
 *
 * Not a convincing concert hall — a gentle blur that stops the piece sounding
 * like it was played inside a filing cabinet. Delay lengths are the classic
 * mutually-prime primes, offset per channel so the two sides decorrelate.
 */
function reverb(channel: Float32Array, spread: number, wet: number): Float32Array {
  const combDelays = [1557, 1617, 1491, 1422].map((d) => d + spread);
  const combFeedback = [0.805, 0.797, 0.783, 0.771];
  const allpassDelays = [225 + spread, 556 + spread];

  const out = new Float32Array(channel.length);
  const buffers = combDelays.map((d) => new Float32Array(d));
  const positions = combDelays.map(() => 0);
  // One-pole damping inside each comb: the tail loses its highs first, which is
  // what real rooms do and what keeps a long tail from sounding metallic.
  const damped = combDelays.map(() => 0);
  const damping = 0.28;

  for (let i = 0; i < channel.length; i += 1) {
    const input = channel[i] as number;
    let sum = 0;
    for (let c = 0; c < buffers.length; c += 1) {
      const buffer = buffers[c] as Float32Array;
      const position = positions[c] as number;
      const delayed = buffer[position] as number;
      sum += delayed;
      const filtered = delayed * (1 - damping) + (damped[c] as number) * damping;
      damped[c] = filtered;
      buffer[position] = input + filtered * (combFeedback[c] as number);
      positions[c] = (position + 1) % buffer.length;
    }
    out[i] = sum * 0.25;
  }

  for (const delay of allpassDelays) {
    const buffer = new Float32Array(delay);
    let position = 0;
    const g = 0.5;
    for (let i = 0; i < out.length; i += 1) {
      const delayed = buffer[position] as number;
      const input = out[i] as number;
      const value = -g * input + delayed;
      buffer[position] = input + g * value;
      position = (position + 1) % delay;
      out[i] = value;
    }
  }

  const mixed = new Float32Array(channel.length);
  for (let i = 0; i < channel.length; i += 1) {
    mixed[i] = (channel[i] as number) * (1 - wet) + (out[i] as number) * wet;
  }
  return mixed;
}

/** One-pole low-pass. Takes the glassy edge off the whole mix. */
function lowpass(channel: Float32Array, cutoffHz: number): void {
  const rc = 1 / (2 * Math.PI * cutoffHz);
  const alpha = 1 / SAMPLE_RATE / (rc + 1 / SAMPLE_RATE);
  let previous = 0;
  for (let i = 0; i < channel.length; i += 1) {
    previous += alpha * ((channel[i] as number) - previous);
    channel[i] = previous;
  }
}

/* -------------------------------------------------------------------------- */
/* arrangement                                                                 */
/* -------------------------------------------------------------------------- */

/** A chord as a root and the notes above it, all as absolute MIDI numbers. */
type Chord = { bass: number; notes: number[]; melody: number[] };

function chord(bassName: string, noteNames: string[], melodyNames: string[]): Chord {
  return {
    bass: midi(bassName),
    notes: noteNames.map(midi),
    melody: melodyNames.map(midi),
  };
}

type Piece = {
  slug: string;
  title: string;
  description: string;
  bpm: number;
  seed: number;
  moodTags: MusicTrackMeta['moodTags'];
  /** Which key it is in, for the licence note and nothing else. */
  key: string;
  /** Eight beats each: one chord per phrase, which is what makes the grid true. */
  progression: Chord[];
  /** How many times the progression is played. Length ≈ phrases × 8 beats. */
  repeats: number;
  /** Bell arpeggios over the middle section. */
  arpeggio: boolean;
  /** How present the pad is. Hymn-like pieces lean on it. */
  padLevel: number;
  reverbWet: number;
};

/**
 * Eight pieces, chosen for range rather than for count: two that lift, three
 * that sit still, two that are frankly hymn-shaped, and one that moves.
 *
 * Every progression is diatonic and resolves home. Nothing modulates, nothing
 * surprises: this is music to hold a room, not to be noticed.
 */
const PIECES: Piece[] = [
  {
    slug: 'morning-light',
    title: 'Morning Light',
    description: 'Warm and unhurried, with a melody that keeps opening upward.',
    bpm: 72,
    seed: 1042,
    moodTags: ['hopeful', 'warm'],
    key: 'F major',
    repeats: 3,
    arpeggio: false,
    padLevel: 0.5,
    reverbWet: 0.3,
    progression: [
      chord('F2', ['F3', 'A3', 'C4'], ['F4', 'A4', 'C5', 'A4']),
      chord('C3', ['E3', 'G3', 'C4'], ['G4', 'E4', 'G4', 'C5']),
      chord('D3', ['F3', 'A3', 'D4'], ['A4', 'D5', 'C5', 'A4']),
      chord('A#2', ['D3', 'F3', 'A#3'], ['F4', 'A#4', 'D5', 'F5']),
      chord('F2', ['F3', 'A3', 'C4'], ['C5', 'A4', 'F4', 'A4']),
      chord('G2', ['A#3', 'D4', 'G4'], ['D5', 'A#4', 'G4', 'A#4']),
      chord('A#2', ['D3', 'F3', 'A#3'], ['A#4', 'D5', 'F5', 'D5']),
      chord('C3', ['E3', 'G3', 'C4'], ['C5', 'G4', 'E4', 'G4']),
    ],
  },
  {
    slug: 'gentle-river',
    title: 'Gentle River',
    description: 'A slow current in D minor. Nothing arrives, nothing leaves.',
    bpm: 64,
    seed: 20713,
    moodTags: ['peaceful', 'reflective'],
    key: 'D minor',
    repeats: 3,
    arpeggio: true,
    padLevel: 0.6,
    reverbWet: 0.36,
    progression: [
      chord('D2', ['D3', 'F3', 'A3'], ['D4', 'F4', 'A4', 'F4']),
      chord('A#2', ['D3', 'F3', 'A#3'], ['F4', 'A#4', 'A4', 'F4']),
      chord('F2', ['F3', 'A3', 'C4'], ['A4', 'C5', 'A4', 'F4']),
      chord('C3', ['E3', 'G3', 'C4'], ['G4', 'C5', 'G4', 'E4']),
      chord('D2', ['D3', 'F3', 'A3'], ['A4', 'F4', 'D4', 'F4']),
      chord('G2', ['A#2', 'D3', 'G3'], ['A#4', 'D5', 'A#4', 'G4']),
      chord('A2', ['C#3', 'E3', 'A3'], ['E4', 'A4', 'C#5', 'A4']),
      chord('D2', ['D3', 'F3', 'A3'], ['D5', 'A4', 'F4', 'D4']),
    ],
  },
  {
    slug: 'evensong',
    title: 'Evensong',
    description: 'Hymn-shaped and unmistakably an ending. Sustained, not sentimental.',
    bpm: 60,
    seed: 7781,
    moodTags: ['peaceful', 'warm'],
    key: 'B-flat major',
    repeats: 3,
    arpeggio: false,
    padLevel: 0.78,
    reverbWet: 0.4,
    progression: [
      chord('A#2', ['D3', 'F3', 'A#3'], ['A#4', 'D5', 'F5', 'D5']),
      chord('F2', ['A2', 'C3', 'F3'], ['C5', 'A4', 'F4', 'A4']),
      chord('G2', ['A#2', 'D3', 'G3'], ['D5', 'A#4', 'G4', 'A#4']),
      chord('D#2', ['G2', 'A#2', 'D#3'], ['A#4', 'G4', 'D#4', 'G4']),
      chord('A#2', ['D3', 'F3', 'A#3'], ['F4', 'A#4', 'D5', 'A#4']),
      chord('C3', ['E3', 'G3', 'C4'], ['G4', 'C5', 'E5', 'C5']),
      chord('F2', ['A2', 'C3', 'F3'], ['C5', 'A4', 'F4', 'C4']),
      chord('A#2', ['D3', 'F3', 'A#3'], ['A#4', 'F4', 'D4', 'A#3']),
    ],
  },
  {
    slug: 'quiet-hours',
    title: 'Quiet Hours',
    description: 'Sparse and thoughtful, for the parts of a life that were private.',
    bpm: 63,
    seed: 33119,
    moodTags: ['reflective', 'peaceful'],
    key: 'A minor',
    repeats: 3,
    arpeggio: false,
    padLevel: 0.45,
    reverbWet: 0.34,
    progression: [
      chord('A2', ['C3', 'E3', 'A3'], ['A4', 'C5', 'B4', 'E4']),
      chord('F2', ['A2', 'C3', 'F3'], ['C5', 'A4', 'F4', 'A4']),
      chord('C3', ['E3', 'G3', 'C4'], ['G4', 'E5', 'C5', 'G4']),
      chord('G2', ['B2', 'D3', 'G3'], ['D5', 'B4', 'G4', 'B4']),
      chord('A2', ['C3', 'E3', 'A3'], ['E5', 'C5', 'A4', 'C5']),
      chord('D3', ['F3', 'A3', 'D4'], ['A4', 'D5', 'F5', 'D5']),
      chord('E3', ['G#3', 'B3', 'E4'], ['B4', 'E5', 'G#4', 'B4']),
      chord('A2', ['C3', 'E3', 'A3'], ['A4', 'E4', 'C4', 'A3']),
    ],
  },
  {
    slug: 'the-long-meadow',
    title: 'The Long Meadow',
    description: 'Open and outdoors. Suits a life spent mostly out of the house.',
    bpm: 76,
    seed: 5502,
    moodTags: ['hopeful', 'warm'],
    key: 'G major',
    repeats: 4,
    arpeggio: true,
    padLevel: 0.42,
    reverbWet: 0.3,
    progression: [
      chord('G2', ['B2', 'D3', 'G3'], ['G4', 'B4', 'D5', 'B4']),
      chord('D3', ['F#3', 'A3', 'D4'], ['A4', 'D5', 'F#5', 'D5']),
      chord('E3', ['G3', 'B3', 'E4'], ['B4', 'E5', 'D5', 'B4']),
      chord('C3', ['E3', 'G3', 'C4'], ['G4', 'C5', 'E5', 'C5']),
      chord('G2', ['B2', 'D3', 'G3'], ['D5', 'B4', 'G4', 'B4']),
      chord('C3', ['E3', 'G3', 'C4'], ['E5', 'C5', 'G4', 'C5']),
      chord('D3', ['F#3', 'A3', 'D4'], ['F#5', 'D5', 'A4', 'D5']),
      chord('G2', ['B2', 'D3', 'G3'], ['G5', 'D5', 'B4', 'G4']),
    ],
  },
  {
    slug: 'harbour-light',
    title: 'Harbour Light',
    description: 'Steady and reassuring, the way a hand on a shoulder is.',
    bpm: 69,
    seed: 8894,
    moodTags: ['warm', 'hopeful'],
    key: 'C major',
    repeats: 3,
    arpeggio: false,
    padLevel: 0.55,
    reverbWet: 0.32,
    progression: [
      chord('C3', ['E3', 'G3', 'C4'], ['C5', 'E5', 'G4', 'E5']),
      chord('A2', ['C3', 'E3', 'A3'], ['A4', 'C5', 'E5', 'C5']),
      chord('F2', ['A2', 'C3', 'F3'], ['C5', 'F5', 'A4', 'F4']),
      chord('G2', ['B2', 'D3', 'G3'], ['B4', 'D5', 'G5', 'D5']),
      chord('C3', ['E3', 'G3', 'C4'], ['E5', 'C5', 'G4', 'C5']),
      chord('E3', ['G3', 'B3', 'E4'], ['B4', 'E5', 'G4', 'B4']),
      chord('F2', ['A2', 'C3', 'F3'], ['A4', 'C5', 'F5', 'C5']),
      chord('G2', ['B2', 'D3', 'G3'], ['D5', 'B4', 'G4', 'D4']),
    ],
  },
  {
    slug: 'after-the-rain',
    title: 'After the Rain',
    description: 'Bells over a low pedal. Reflective without being heavy.',
    bpm: 70,
    seed: 61203,
    moodTags: ['reflective', 'hopeful'],
    key: 'E minor',
    repeats: 3,
    arpeggio: true,
    padLevel: 0.5,
    reverbWet: 0.38,
    progression: [
      chord('E2', ['G2', 'B2', 'E3'], ['E4', 'G4', 'B4', 'G4']),
      chord('C3', ['E3', 'G3', 'C4'], ['G4', 'C5', 'E5', 'C5']),
      chord('G2', ['B2', 'D3', 'G3'], ['D5', 'B4', 'G4', 'B4']),
      chord('D3', ['F#3', 'A3', 'D4'], ['A4', 'D5', 'F#5', 'D5']),
      chord('E2', ['G2', 'B2', 'E3'], ['B4', 'G4', 'E4', 'G4']),
      chord('A2', ['C3', 'E3', 'A3'], ['E5', 'C5', 'A4', 'C5']),
      chord('B2', ['D#3', 'F#3', 'B3'], ['F#5', 'D#5', 'B4', 'F#4']),
      chord('E2', ['G2', 'B2', 'E3'], ['E5', 'B4', 'G4', 'E4']),
    ],
  },
  {
    slug: 'all-the-years',
    title: 'All the Years',
    description: 'The longest of them, and the one that carries a whole life.',
    bpm: 74,
    seed: 14407,
    moodTags: ['warm', 'reflective'],
    key: 'D major',
    repeats: 4,
    arpeggio: false,
    padLevel: 0.52,
    reverbWet: 0.33,
    progression: [
      chord('D3', ['F#3', 'A3', 'D4'], ['D5', 'F#5', 'A4', 'F#5']),
      chord('A2', ['C#3', 'E3', 'A3'], ['E5', 'C#5', 'A4', 'C#5']),
      chord('B2', ['D3', 'F#3', 'B3'], ['F#5', 'B4', 'D5', 'B4']),
      chord('G2', ['B2', 'D3', 'G3'], ['D5', 'G4', 'B4', 'G4']),
      chord('D3', ['F#3', 'A3', 'D4'], ['A4', 'D5', 'F#5', 'D5']),
      chord('G2', ['B2', 'D3', 'G3'], ['B4', 'D5', 'G5', 'D5']),
      chord('A2', ['C#3', 'E3', 'A3'], ['C#5', 'E5', 'A4', 'E5']),
      chord('D3', ['F#3', 'A3', 'D4'], ['D5', 'A4', 'F#4', 'D4']),
    ],
  },
];

/**
 * Turn a piece into a list of notes.
 *
 * The shape is the same on every track and is the oldest one there is: state
 * it, state it again with more of the arrangement, take something away, end
 * where it began. The first pass through the progression is pad and bass alone,
 * the last is thinned out again, and the final chord is held long enough for
 * the room to know it is over.
 */
function arrange(piece: Piece): { notes: NoteEvent[]; endSec: number } {
  const random = rng(piece.seed);
  const beatSec = 60 / piece.bpm;
  const phraseSec = beatSec * 8;
  const notes: NoteEvent[] = [];
  const chords = piece.progression;

  let time = 0;
  for (let repeat = 0; repeat < piece.repeats; repeat += 1) {
    const first = repeat === 0;
    const last = repeat === piece.repeats - 1;
    // The middle passes carry the melody; the first is an introduction and the
    // last lets go of it again.
    const melodic = !first;
    const full = !first && !last;

    for (const [index, current] of chords.entries()) {
      const start = time;
      const finalChord = last && index === chords.length - 1;

      // Bass: the root, once, held across the phrase.
      notes.push({
        midi: current.bass,
        startSec: start,
        holdSec: finalChord ? phraseSec * 1.6 : phraseSec * 0.92,
        velocity: 0.85,
        timbre: BASS,
        pan: 0,
      });

      // Pad: the chord, arriving slowly and leaving slowly.
      for (const [voice, note] of current.notes.entries()) {
        notes.push({
          midi: note,
          startSec: start + voice * 0.012,
          holdSec: (finalChord ? phraseSec * 1.5 : phraseSec * 0.95) as number,
          velocity: piece.padLevel * (0.9 + random() * 0.15),
          timbre: PAD,
          pan: -0.22 + voice * 0.22,
        });
      }

      // The chord again, struck, on the downbeat and the half — this is what
      // the ear hears as "someone is playing this".
      const strikes = full ? [0, 4] : [0];
      for (const beat of strikes) {
        for (const [voice, note] of current.notes.entries()) {
          notes.push({
            midi: note + (voice === current.notes.length - 1 ? 12 : 0),
            startSec: start + beat * beatSec + voice * 0.016,
            holdSec: beatSec * 3.4,
            velocity: (beat === 0 ? 0.5 : 0.36) * (0.9 + random() * 0.2),
            timbre: PIANO,
            pan: -0.1 + voice * 0.1,
          });
        }
      }

      // Melody: four notes across eight beats, held long. Slow enough that
      // nothing is ever competing with a photograph for attention.
      if (melodic) {
        const line = current.melody;
        const placements = last ? [0, 3, 6] : [0, 2.5, 4.5, 6.5];
        for (const [step, at] of placements.entries()) {
          const note = line[step % line.length] as number;
          const jitter = (random() - 0.5) * 0.012;
          notes.push({
            midi: note,
            startSec: start + at * beatSec + jitter,
            holdSec: beatSec * (last ? 2.6 : 1.9),
            velocity: (last ? 0.4 : 0.52) * (0.86 + random() * 0.24),
            timbre: PIANO,
            pan: 0.06,
          });
        }
      }

      // Arpeggio: eighth-note bells over the middle section only.
      if (piece.arpeggio && full) {
        const shape = [...current.notes, (current.notes[1] as number) + 12];
        for (let step = 0; step < 8; step += 1) {
          const note = (shape[step % shape.length] as number) + 12;
          notes.push({
            midi: note,
            startSec: start + step * beatSec,
            holdSec: beatSec * 0.9,
            velocity: 0.13 * (0.8 + random() * 0.4),
            timbre: BELL,
            pan: -0.3 + (step % 3) * 0.3,
          });
        }
      }

      time += phraseSec;
    }
  }

  // Room for the last chord's tail. Nothing is more obviously synthetic than a
  // piece of music that stops the instant the last note is released.
  return { notes, endSec: time + 5 };
}

/* -------------------------------------------------------------------------- */
/* rendering                                                                   */
/* -------------------------------------------------------------------------- */

function renderPiece(piece: Piece): { wav: Buffer; durationSec: number } {
  const { notes, endSec } = arrange(piece);
  const frames = Math.ceil(endSec * SAMPLE_RATE);
  let left = new Float32Array(frames);
  let right = new Float32Array(frames);

  for (const note of notes) renderNote(left, right, note);

  lowpass(left, 7200);
  lowpass(right, 7200);
  left = reverb(left, 0, piece.reverbWet);
  right = reverb(right, 23, piece.reverbWet);

  // Normalise to a comfortable peak. The renderer's loudnorm pass has the final
  // say on level; this only makes sure the AAC encoder never sees a clip.
  let peak = 0;
  for (let i = 0; i < frames; i += 1) {
    peak = Math.max(peak, Math.abs(left[i] as number), Math.abs(right[i] as number));
  }
  const gain = peak > 0 ? 0.72 / peak : 1;

  // A short fade at each end so the encoder has nothing to click on.
  const fadeIn = Math.round(SAMPLE_RATE * 0.6);
  const fadeOut = Math.round(SAMPLE_RATE * 3.5);
  for (let i = 0; i < frames; i += 1) {
    let envelope = gain;
    if (i < fadeIn) envelope *= i / fadeIn;
    if (i > frames - fadeOut) envelope *= Math.max(0, (frames - i) / fadeOut);
    left[i] = (left[i] as number) * envelope;
    right[i] = (right[i] as number) * envelope;
  }

  return {
    wav: encodeWav([left, right], { sampleRate: SAMPLE_RATE, channels: 2 }),
    durationSec: frames / SAMPLE_RATE,
  };
}

/* -------------------------------------------------------------------------- */
/* provenance                                                                  */
/* -------------------------------------------------------------------------- */

const LICENSE_NOTE =
  'Original work, generated by scripts/make-music.ts in this repository and ' +
  'dedicated to the public domain under CC0 1.0. No performer, no sample ' +
  'library and no third-party recording is involved: every sample is computed ' +
  'from the chord progression and tempo written in that script, so the audio ' +
  'can be reproduced exactly by re-running it. There is nothing here for ' +
  'anyone to claim a licence fee on.';

function licenseText(piece: Piece, durationSec: number): string {
  return [
    `${piece.title} — licence and provenance`,
    '',
    'Licence: CC0 1.0 Universal (public domain dedication).',
    'https://creativecommons.org/publicdomain/zero/1.0/',
    '',
    'Provenance',
    '----------',
    'This recording was not obtained from anywhere. It was synthesised by',
    'scripts/make-music.ts in this repository: a small additive synthesiser',
    'renders the chord progression and melody written in that file, at the',
    'tempo written in that file, through a reverb written in that file, and',
    'ffmpeg encodes the result to AAC.',
    '',
    `  key       ${piece.key}`,
    `  tempo     ${piece.bpm} BPM`,
    `  length    ${durationSec.toFixed(1)} seconds`,
    `  seed      ${piece.seed} (deterministic — re-running reproduces this file)`,
    '',
    'Because the work is entirely original and machine-generated from that',
    'source, it carries no third-party rights: no composition licence, no',
    'master recording licence, no performing rights, no attribution required.',
    'A family may include it in a video and share that video anywhere.',
    '',
    'The CC0 dedication is made by the authors of this repository.',
  ].join('\n');
}

/* -------------------------------------------------------------------------- */
/* the script                                                                  */
/* -------------------------------------------------------------------------- */

async function probeDuration(file: string): Promise<number> {
  const result = await runFfprobe([
    '-v',
    'error',
    '-show_entries',
    'format=duration',
    '-of',
    'default=nw=1:nk=1',
    file,
  ]);
  return Number.parseFloat(result.stdout.trim());
}

export async function makeTrack(piece: Piece): Promise<MusicTrackMeta> {
  const dir = path.join(MUSIC_LIBRARY_DIR, piece.slug);
  await mkdir(dir, { recursive: true });

  const wavFile = path.join(dir, 'audio.wav');
  const audioFile = path.join(dir, 'audio.m4a');

  const { wav } = renderPiece(piece);
  await writeFile(wavFile, wav);
  await runFfmpeg(
    [
      '-hide_banner',
      '-nostdin',
      '-y',
      '-i',
      wavFile,
      '-c:a',
      'aac',
      '-b:a',
      BITRATE,
      '-ar',
      '44100',
      '-ac',
      '2',
      '-movflags',
      '+faststart',
      audioFile,
    ],
    { timeoutMs: 300_000 },
  );
  await rm(wavFile, { force: true });

  // The encoded length, not the synthesised one: the beat grid has to describe
  // the file a family will actually hear.
  const durationSec = Math.round((await probeDuration(audioFile)) * 1000) / 1000;

  const meta: MusicTrackMeta = {
    slug: piece.slug,
    title: piece.title,
    artist: 'Celebration of Life toolkit (generated)',
    durationSec,
    bpm: piece.bpm,
    licenseKind: 'public-domain',
    licenseNote: LICENSE_NOTE,
    acquiredAt: new Date().toISOString().slice(0, 10),
    verifiedBy: 'scripts/make-music.ts',
    moodTags: piece.moodTags,
    traditionTags: [],
    description: piece.description,
    beatGrid: beatGridFromBpm(piece.bpm, durationSec),
    audioFile: 'audio.m4a',
    mime: 'audio/mp4',
  };

  await writeFile(path.join(dir, 'meta.json'), `${JSON.stringify(meta, null, 2)}\n`);
  await writeFile(path.join(dir, 'LICENSE.txt'), `${licenseText(piece, durationSec)}\n`);
  return meta;
}

export async function makeMusicLibrary(): Promise<MusicTrackMeta[]> {
  const out: MusicTrackMeta[] = [];
  for (const piece of PIECES) {
    const startedAt = Date.now();
    const meta = await makeTrack(piece);
    const file = path.join(MUSIC_LIBRARY_DIR, piece.slug, 'audio.m4a');
    const size = (await stat(file)).size;
    console.log(
      `${meta.slug.padEnd(18)} ${meta.durationSec.toFixed(1)}s  ${meta.bpm} BPM  ` +
        `${(size / 1024 / 1024).toFixed(2)} MB  ${((Date.now() - startedAt) / 1000).toFixed(1)}s`,
    );
    if (size > 3 * 1024 * 1024) {
      console.warn(`  ! ${meta.slug} is over 3 MB — too big to keep in the repository.`);
    }
    out.push(meta);
  }
  return out;
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === path.resolve(here, 'make-music.ts');
if (invokedDirectly) {
  makeMusicLibrary()
    .then((tracks) => {
      console.log(`\n${tracks.length} tracks written to content/music-library.`);
    })
    .catch((error: unknown) => {
      console.error(error);
      process.exitCode = 1;
    });
}
