/**
 * The program, as plain text.
 *
 * Funeral homes set programs themselves, in whatever they already use, and they
 * ask for the words in an email. This is the same document the print page
 * renders, generated by the same code, with no markup to lose on the way.
 */
import { authorizeOrganizer, currentProgram, programToText } from '@col/core';
import { getById, memorials } from '@col/db';
import { db } from '@/server/db';
import { readSession } from '@/server/session';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const forbidden = () =>
  new Response('Not available.', { status: 403, headers: { 'cache-control': 'no-store' } });

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ memorialId: string }> },
): Promise<Response> {
  const { memorialId } = await params;

  const session = await readSession();
  if (!session || !authorizeOrganizer(db(), session, memorialId).ok) return forbidden();

  const memorial = getById(db(), memorials, memorialId);
  if (!memorial || memorial.deletedAt != null) return forbidden();

  const { doc } = currentProgram(db(), memorial);

  return new Response(programToText(doc), {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'private, no-store',
      'content-disposition': 'inline; filename="order-of-service.txt"',
    },
  });
}
